export const BondingCurveABI = [
  {
    inputs: [{ name: '_feeRecipient', type: 'address' }],
    stateMutability: 'nonpayable',
    type: 'constructor',
  },
  {
    inputs: [],
    name: 'INITIAL_VIRTUAL_CRO',
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'TOTAL_SUPPLY',
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'GRADUATION_THRESHOLD',
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'TRADING_FEE_BPS',
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { name: 'token', type: 'address' },
      { name: 'minTokensOut', type: 'uint256' },
    ],
    name: 'buy',
    outputs: [],
    stateMutability: 'payable',
    type: 'function',
  },
  {
    inputs: [
      { name: 'token', type: 'address' },
      { name: 'tokenAmount', type: 'uint256' },
      { name: 'minCroOut', type: 'uint256' },
    ],
    name: 'sell',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ name: 'token', type: 'address' }],
    name: 'getCurrentPrice',
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { name: 'token', type: 'address' },
      { name: 'croAmount', type: 'uint256' },
    ],
    name: 'getTokensForCro',
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { name: 'token', type: 'address' },
      { name: 'tokenAmount', type: 'uint256' },
    ],
    name: 'getCroForTokens',
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ name: 'token', type: 'address' }],
    name: 'getCurveState',
    outputs: [
      { name: 'virtualCroReserve', type: 'uint256' },
      { name: 'virtualTokenReserve', type: 'uint256' },
      { name: 'realCroReserve', type: 'uint256' },
      { name: 'tokensSold', type: 'uint256' },
      { name: 'currentPrice', type: 'uint256' },
      { name: 'progressBps', type: 'uint256' },
      { name: 'canGraduate', type: 'bool' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ name: '', type: 'address' }],
    name: 'curves',
    outputs: [
      { name: 'virtualCroReserve', type: 'uint256' },
      { name: 'virtualTokenReserve', type: 'uint256' },
      { name: 'realCroReserve', type: 'uint256' },
      { name: 'tokensSold', type: 'uint256' },
      { name: 'creator', type: 'address' },
      { name: 'initialized', type: 'bool' },
      { name: 'graduated', type: 'bool' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: 'token', type: 'address' },
      { indexed: true, name: 'buyer', type: 'address' },
      { indexed: false, name: 'croIn', type: 'uint256' },
      { indexed: false, name: 'tokensOut', type: 'uint256' },
      { indexed: false, name: 'newPrice', type: 'uint256' },
    ],
    name: 'TokenBought',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: 'token', type: 'address' },
      { indexed: true, name: 'seller', type: 'address' },
      { indexed: false, name: 'tokensIn', type: 'uint256' },
      { indexed: false, name: 'croOut', type: 'uint256' },
      { indexed: false, name: 'newPrice', type: 'uint256' },
    ],
    name: 'TokenSold',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: 'token', type: 'address' },
      { indexed: false, name: 'croCollected', type: 'uint256' },
    ],
    name: 'ReadyToGraduate',
    type: 'event',
  },
] as const
